<a href="https://colab.research.google.com/github/kiranpathak-dev/python-cheat-sheet/blob/main/python_cheat_sheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Arithmetic Operators

print (10 + 5)
print(10 - 5)
print(10 * 5)
print(10 / 5)
print(10 // 5)
print(10 % 5)
print(10 ** 5)

"""
// is called the floor division operator. x // y gives the quotient when x is divided by y. For example, 8 // 3 is 2.
% is called the modulus operator. x % y gives the remainder when x is divided by y. For example, 10 % 3 is 1.
** is called the exponentiation operator. x ** y returns
"""

15
5
50
2.0
2
0
100000

'\n// is called the floor division operator. x // y gives the quotient when x is divided by y. For example, 8 // 3 is 2.\n% is called the modulus operator. x % y gives the remainder when x is divided by y. For example, 10 % 3 is 1.\n** is called the exponentiation operator. x ** y returns \n'

In [ ]:
# Relational Operators
print (10 > 5)
print(10 < 5)
print(10 >= 5)
print(10 <= 5)
print(10 == 5)
print(10 != 5)

True
False
True
False
False
True

In [ ]:
# Logical Operators
print(10 > 5 and 10 < 5)
print(10 > 5 or 10 < 5)
print(not(10 > 5))

False
True
False

In [ ]:
# Operator Chanining
print(10 > 5 > 3) # is the same as (10 > 5 and 5 > 3)
print(10 > 5 < 3)

True
False

In [ ]:
# type
print(type(10))
print(type(10.5))
print(type(10 + 5j))

<class 'int'>
<class 'float'>
<class 'complex'>

### Precendence![Screenshot 2025-03-10 012747.png]()

In [ ]:
# Precedence
(3 ** 2) * 4 - 4  #Python evaluates expressions from left to right.

32

Similar to arithmetic operators, logical operators also have precedence. Boolean expressions are also going to evaluated from left to right.
![Screenshot 2025-03-10 013116.png]()

### Strings
Quotes: single, double and triple

"this is a string"
'this is also a string'
'1 + 1 = 2'
"!, ?, _, @ are special characters"
"if you need to use apostrophe ('), you can use double quotes"

It is a good practice to stick to either single or double quotes when using strings. Interestingly, Python also supports triple quotes ''', especially for multi-line strings

In [ ]:
x = '''first line
second line
third line'''
print(x)

first line
second line
third line

In [ ]:
len(x)

33

In [ ]:
# Concatenation
str1 = 'first'
str2 = ' second'
str1 + str2

'first second'

In [ ]:
# Replication
str = "hello"
str*5

'hellohellohellohellohello'

In [ ]:
# Comparison
x = 'python'
print(x == 'python', x == 'nohtyp')

True False

In [ ]:
print('good' > 'bad')
print('nine' < 'one' )
print('a' < 'ab' < 'abc' < 'b')
print('a' < 'A')

True
True
True
False

It is clear from the above examples that the length of the string is not a metric used by Python to compare strings. Instead, Python uses the familiar alphabetical ordering to compare two strings. More precisely it employs what is known as lexicographic ordering:

Lexicographic ordering

The first characters from the two strings are compared. If they differ this determines the outcome of the comparison. If they are equal, then the second character of both the strings are compared. This process continues until either string is exhausted.

In [ ]:
print(ord('a'), ord('b'))
print(ord('A'), ord('B'))

97 98
65 66

In [ ]:
#Substrings
a ='good'
b = 'very good'
a in  b

True

In [ ]:
b in a

False

![Screenshot 2025-03-10 014710.png]()

In [ ]:
# Indexing

word = 'world'
print(word[0])
print(word[1])
print(word[2])
print(word[3])
print(word[4])

w
o
r
l
d

In [ ]:
# slicing
word[0 : 4 : 2]   # start, stop, step

'wr'

In [ ]:
word[ : 3]

'wor'

In [ ]:
word[-4:-1 ]

'orl'

In [ ]:
# Strings are immutable. One or more characters in the string literal present in word cannot be modified in-place.

word = 'some string'
word[0] = 'S'

#The interpreter throws a TypeError with the following error message: 'str' object does not support item assignment.

TypeError: 'str' object does not support item assignment

In [ ]:
sentence = input()
# cap = sentence[0].upper() + sentence[1:]
cap = sentence.capitalize()
print(cap)

this is a chair.
This is a chair.

In [ ]:
# name is some pre-defined string
name = 'kiran123'
valid = name.isalpha()
print(valid)

False

### Variables

In [ ]:
x = 1
y = 100.
z = "good"
print('The initial value of x is', x)

x = 2
print('The value after updating x is', x)

The initial value of x is 1
The value after updating x is 2

In [ ]:
#Multiple Assignment
z, y = 2, 3

In [ ]:
z, y

(2, 3)

In [ ]:
x = y = z = 10
print(x,y,z)

10 10 10

![Screenshot 2025-03-10 015854.png]()

In [ ]:
# Deleting variables
del x

### Input

In [ ]:
x = input()
print('The input entered by the user is', x)

2
The input entered by the user is 2

In [ ]:
x = input('Enter an integer between 0 and 10: ')
print('The number entered by the user is', x)

Enter an integer between 0 and 10: 4
The number entered by the user is 4

In [ ]:
# type conversion
x = '123'
print('The type of x is', type(x))
y = int(x)
print('The type of y is', type(y))

The type of x is <class 'str'>
The type of y is <class 'int'>

In [ ]:
x = int(input())
print('The integer entered by the user is', x)
print(type ( x))

6
The integer entered by the user is 6
<class 'int'>

In [ ]:
print(round(1.9))
print(abs(-1.2))
print(pow(2,3))
print(int('123'))
print(int(1.2))
print(int(-2.2))

2
1.2
8
123
1
-2

In [ ]:
#isinstance() is used to check if an object is of a specified type.
isinstance(3, int)

True

### Conditional

In [ ]:
x = int(input())
if x > 0:
  print(f"positive integer: {x}")
elif x < 0:
  print(f"negative integer: {x}")
else:
  print(f"zero: {x}")

8
positive integer: 8

### Library

In [ ]:
import calendar
calendar.prmonth(2024,3)

     March 2024
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31

In [ ]:
from time import ctime
print('The current time is:', ctime())

The current time is: Sun Mar  9 20:43:01 2025

In [ ]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!

### while loop

In [ ]:
# Initialize
num = int(input())
max_num = 0
# Loop
while num >= 0:
    if num > max_num:
        max_num = num
    num = int(input())
# Print output
print(max_num)

2
3
6
0
-1
6

### Loop Control Statements

*break* and *continue* are keywords in Python and are associated with loops.

The *break* statement is used to exit out of a loop without executing any code that comes below it. For example:

In [ ]:
num = 1
while True:
    if (num % 2 == 0) and (num % 3 == 0) and (num % 4 == 0):
        break
    num = num + 1
print(num)

12

The *continue* statement is used to move to the next iteration of the loop, skipping whatever code comes below it. For example:

In [ ]:
x = 0
while x < 50:
    x = x + 1
    if x % 3 != 0:
        continue
    print(x)

3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48

### for loop

In [ ]:
for i in range(10, 101, 10):   # start, stop (+1) , step
  print(i)

10
20
30
40
50
60
70
80
90
100

In [ ]:
for i in range(10, 5, -1):
    print(i)

10
9
8
7
6

In [ ]:
for i in range(10, 5, -1):
    print(i)

10
9
8
7
6

### Iterating through Strings

In [ ]:
word = 'good'
for char in word:
  print(char)

g
o
o
d

In [ ]:
word = 'good'
count = 0
for char in word:
  print(char, 'occurs at position', count, 'in the string', word)
  count += 1

g occurs at position 0 in the string good
o occurs at position 1 in the string good
o occurs at position 2 in the string good
d occurs at position 3 in the string good

In [ ]:
#Find the number of ordered pairs of positive integers whose product is 100. Note that order matters: (2, 50) and (50, 2) are two different pairs.
for a in range(1, 101):
  for b in range(1, 101):
    if a * b == 100:
      count +=1
print(count)

13

In [ ]:
n = int(input())
for i in range(1, n):
    print(i, end = ',')
print(n)

9
1,2,3,4,5,6,7,8,9

### sep

In [ ]:
print('this', 'is', 'cool')

print('this', 'is', 'cool', sep = ',')

print('this', 'is', 'cool', sep = '')

this is cool
this,is,cool
thisiscool

In [ ]:
# f-strings
name = input()
print(f'Hi, {name}!')

kiran
Hi, kiran!

In [ ]:
name = input()
print('Hi, {}!'.format(name))

kiran
Hi, kiran!

In [ ]:
x = int(input())
print(f'Multiplication table for {x}')
for i in range(1, 11):
    print(f'{x} X {i} \t=\t {x * i}')

#same with .format()
# x = int(input())
# for i in range(1, 11):
#     print('{} X {} \t=\t {}'.format(x, i, x * i))

6
Multiplication table for 6
6 X 1 	=	 6
6 X 2 	=	 12
6 X 3 	=	 18
6 X 4 	=	 24
6 X 5 	=	 30
6 X 6 	=	 36
6 X 7 	=	 42
6 X 8 	=	 48
6 X 9 	=	 54
6 X 10 	=	 60

In [ ]:
pi_approx = 22 / 7
print(f'The value of pi is approximately {pi_approx:.2f}')

The value of pi is approximately 3.14

In [ ]:
import random
print(random.choice('HT'))

H

In [ ]:
import random
n = int(input())
heads = 0
for i in range(n):
    toss = random.choice('HT')
    if toss == 'H':
        heads += 1
print(f'P(H) = {heads / n}')

5
P(H) = 0.6

In [ ]:
import random
print(random.randint(1, 6))   # randint a <= n <= b

3

### function

In [ ]:
def square(x):
  return x**2

In [ ]:
square(5)

25

In [ ]:
# Functions could have no return value:
def foo():
    print("I don't like talking to the outside world!")

foo()

I don't like talking to the outside world!

In [ ]:
# Functions could have multiple return statements, but the moment the first return is executed, control exits from the function:
def evenOrOdd(n):
    if n % 2 == 0:
        return 'even'
    else:
        return 'odd'

print(evenOrOdd(10))
print(evenOrOdd(11))

In [ ]:
# Functions could return multiple values:
# Accept only positive floating point numbers
def bound(x):
    lower = int(x)
    upper = lower + 1
    return lower, upper

y = 7.3
l, u = bound(y)
print(f'{l} < {y} < {u}')

7 < 7.3 < 8

In [ ]:
def square(x):
    """Return the square of x."""
    return x ** 2
square(5)

25

In [ ]:
def isRight(x, y, z):
    if x ** 2 + y ** 2 == z ** 2:
        return True
    return False

print(isRight(3, 4, 5))
print(isRight(5, 4, 3))

True
False

In [ ]:
# the default parameter must always come at the end of the list of parameters.
def distance(x, y, metric = 'manhattan'):
    if metric == 'manhattan':
        return abs(x) + abs(y)
    elif metric == 'euclidean':
        return pow(x ** 2 + y ** 2, 0.5)

print(distance(3, 4))



#### Alarm! Wrong code snippet! ####
# def distance(metric = 'manhattan', x, y):  #defaulat parameter as first - wrong
#     if metric == 'manhattan':
#         return abs(x) + abs(y)
#     elif metric == 'euclidean':
#         return pow(x ** 2 + y ** 2, 0.5)
#### Alarm! Wrong code snippet! ####

7

In [ ]:
def foo():
    g = 1
    print('This is a veritable fortress. None can enter here.')
    print('\N{smirking face}')

foo()
print(g)

This is a veritable fortress. None can enter here.
😏

NameError: name 'g' is not defined

In [ ]:
### Variant-1
def foo():
    x = 1
    print('I can access both x and y')
    print(f'x = {x}, y = {y}')

y = 10
foo()

I can access both x and y
x = 1, y = 10

In [ ]:
del x,y
### Variant-2
def foo():
    x = 1
    print('I can\'t access both x and y')
    print(f'x = {x}, y = {y}')

foo()
y = 10

I can access both x and y

NameError: name 'y' is not defined

In [ ]:
def foo():
    x = 10
    print(f'x inside foo = {x}')

x = 100
foo()
print(f'x outside foo = {x}')

x inside foo = 10
x outside foo = 100

In [ ]:
def foo():
    global x
    print(f'x inside foo = {x}')
    x = x + 1
    print(f'x inside foo = {x}')

x = 10
print(f'x outside foo = {x}')
foo()

# By declaring x to be global inside foo, a new local variable x is not created even though it appears to the left of an assignment statement in line-4.

![Screenshot 2025-03-10 061221.png]()

![Screenshot 2025-03-10 061226.png]()

In [ ]:
def first():
  second()
  print('first')

def second():
  third()
  print('second')

def third():
  print('third')

first()

third
second
first

In [ ]:
#Recursion
def fibo(n):
  if n == 1 or n == 2:
    return 1
  return fibo(n - 1) + fibo(n - 2)

print(fibo(8))

21

In [ ]:
import time

def fibo(n):
    if n == 1 or n == 2:
        return 1
    return fibo(n - 1) + fibo(n - 2)

start = time.time()
fibo(40)
end = time.time()
print(f'It took approximately {round(end - start)} seconds.')

It took approximately 18 seconds.

### List

A list in Python is a data structure that is used to store a sequence of objects. Some examples are given below:

numbers = [1, 2, 3, 4, 5]

letters = ['a', 'b', 'c', 'd']

words = ['this', 'is', 'a', 'list']

mixture = [1, 1.0, '1', True]

In [ ]:
numbers = [1, 2, 3,4,5,6,7]
print(type(numbers))
print(isinstance(numbers, list))

<class 'list'>
True

In [ ]:
print(len(numbers))

7

In [ ]:
# Lists support indexing and slicing. These two operations work exactly the same way as they did for strings:

print(numbers[1])
print(numbers[:5])
print(numbers[:-3])

2
[1, 2, 3, 4, 5]
[1, 2, 3, 4]

In [ ]:
# Iterating
numbers = [1, 2, 3, 4]

#Method-1
for n in numbers:
  print(n)


# Method-2
index = 0
while index < len(numbers):
    print(numbers[index])
    index += 1

# Method-3
for index in range(len(numbers)):
    print(numbers[index])

1
2
3
4
1
2
3
4
1
2
3
4

In [ ]:
# growing a list

list1 = []

list2 = list()

list1 = list1 + [1]
print(list1)
list2 = list2.append(2)
print(list2)

[1]
None

In [ ]:
# Generate the list of positive integers less than 100 that are divisible by 3.
# Method-1
num = 3
nums_div = []
while num < 100:
    nums_div.append(num)
    num += 3
print(nums_div)

# Method-2
nums_div = []
for num in range(3, 100, 3):
    nums_div.append(num)

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]

In [ ]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
list12 = list1 + list2
print(list12)
list21 = list2 + list1
print(list21)

[1, 2, 3, 4, 5, 6]
[4, 5, 6, 1, 2, 3]

In [ ]:
list1 = [0] * 5
print(list1)
list2 = [1, 2, 3] * 3
print(list2)

[0, 0, 0, 0, 0]
[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
l1 = [1, 2, 3]
l2 = [1, 2, 3]
l3 = [3, 2, 1]
print(l1 == l2)
print(l2 == l3)

True
False

Finally, two lists can be compared with the > or the < operator. List comparison works very similar to string comparison, in that it uses lexicographic ordering. We looked at this in the first chapter:

Lexicographic ordering

First element from both lists are compared. If they differ this determines the outcome of the comparison. If they are equal, then the second element of both the lists are compared. This process continues until either list is exhausted.

In [ ]:
print([1, 2] < [2, 1])
print([1] < [1, 2, 3])
print([2, 3, 4] < [3])
print([] < [1])

True
True
True
True

In [ ]:
# sum
a = [1, 2, 3]

sum(a)

6

In [ ]:
min(a), max(a)

(1, 3)

In [ ]:
a = [2, 1, 3]

sorted(a)

[1, 2, 3]

In [ ]:
numbers = list(range(10))
print(numbers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

We are updating a list in-place. Python permits this operation because lists are *mutable*. Contrast this with *strings that are immutable*, which means that they cannot be *updated in-place*. Mutability makes lists powerful; but reckless exercise of power always results in instability as is demonstrated by this notorious example:

In [ ]:
list1 = [1, 2, 3]
list2 = list1
list2[0] = 100
print(list1)
print(list2)

[100, 2, 3]
[100, 2, 3]

In [ ]:
list1 = [1, 2, 3]
list2 = list1
list2[0] = 100
print(list1 is list2)

True

In [ ]:
list1 = [1, 2, 3]
list2 = [1, 2, 3]
print(list1 == list2)
print(list1 is list2)

True
False

This because equality and identity are two different things. In the code, line-3 checks for equality of two lists, line-4 checks if the two lists point to the same object. list1 and list2 point to two different objects and consequently have different identities. But, they store the same sequence of items and are hence equal.

In [ ]:
# How do we create a copy of a list so that updating one doesn't end up changing both? Python provides three ways to do this:
list1 = [1, 2,  3]
list2 = list(list1)
list3 = list1[:]
list4 = list1.copy()

list2[0] = 100
list3[0] = 200
list4[0] = 300

print(list1, list2, list3, list4)
print(list1 is not list2, list1 is not list3, list1 is not list4)

[1, 2, 3] [100, 2, 3] [200, 2, 3] [300, 2, 3]
True True True

In [ ]:
# Snippet-1
def foo():
    L.append(1)

L = [0]
print(f'L before: {L}')
foo()
print(f'L after: {L}')

L before: [0]
L after: [0, 1]

In [ ]:
# random library
import random
runs = random.choices([0, 1, 2, 3, 4, 5, 6], k = 120)
print(type(runs))
print(len(runs))
print(runs)

<class 'list'>
120
[1, 1, 3, 3, 6, 0, 5, 1, 5, 5, 5, 5, 5, 0, 2, 5, 6, 3, 0, 0, 2, 6, 0, 0, 0, 0, 1, 4, 6, 0, 6, 5, 0, 2, 5, 4, 0, 0, 1, 0, 2, 4, 6, 1, 2, 4, 4, 1, 0, 5, 1, 0, 2, 5, 6, 5, 5, 1, 0, 2, 2, 5, 5, 4, 5, 1, 2, 5, 0, 6, 0, 2, 1, 2, 6, 4, 4, 0, 6, 5, 3, 5, 1, 0, 6, 1, 2, 4, 4, 2, 3, 0, 0, 6, 2, 5, 6, 6, 2, 3, 2, 6, 5, 3, 1, 1, 2, 3, 0, 4, 5, 3, 5, 4, 3, 4, 6, 2, 0, 0]

In [ ]:
import random
# choices is distributed over multiple lines
# this is done to improve readability
runs = random.choices([0, 1, 2, 3, 4, 5, 6],
                      weights = [30, 30, 20, 5, 10, 0, 5],
                      k = 120)
for run in [0, 1, 2, 3, 4, 5, 6]:
    print('{} appears {} times'.format(run, runs.count(run)))
print(f'Total number of runs scored = {sum(runs)}')

0 appears 37 times
1 appears 45 times
2 appears 20 times
3 appears 3 times
4 appears 12 times
5 appears 0 times
6 appears 3 times
Total number of runs scored = 160

The weight is the importance given to a run. From the table given above, we see that 0 and 1 occur 30% of the times, 6 occurs 5% of the times and so on. choices function will keep this distribution in mind while picking up items from the input-list.

In [ ]:
first_six_ball = runs.index(6) + 1
print(first_six_ball)

77

###  list methods like append, count, index, insert, pop, reverse, copy, extend

The *count() method* is used to count the occurrences of a specific element within a list. It returns the number of times the specified element appears in the list.

In [ ]:
my_list = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]
count_of_2 = my_list.count(2)  # Returns 2
count_of_5 = my_list.count(5)  # Returns 0, as 5 is not in the list
print(count_of_2)
print(count_of_5)

2
0

In [ ]:
from collections import Counter
my_list = ['a', 'b', 'a', 'c', 'b', 'a']
counts = Counter(my_list)
print(counts) # Returns {'a': 3, 'b': 2, 'c': 1}
print(counts['a']) # Returns 3

Counter({'a': 3, 'b': 2, 'c': 1})
3

In [ ]:
L = [1, 1, 2, 3, 8]
L.insert(4, 5)
print(L)

[1, 1, 2, 3, 5, 8]

*list.insert(index, object)* inserts the object before index in the list. In the code given above, the element 5 is inserted before the index 4 in the list L. Let us try a few more inserts:

In [ ]:
L = [10, 20, 30]
L.insert(0, 5)          # L becomes [5, 10, 20, 30]
L.insert(2, 15)         # L becomes [5, 10, 15, 20, 30]
L.insert(4, 25)         # L becomes [5, 10, 15, 20, 25, 30]
L.insert(len(L), 35)    # L becomes [5, 10, 15, 20, 25, 30, 35]
L.insert(20, 40)        # L becomes [5, 10, 15, 20, 25, 30, 35, 40]

In [ ]:
fruits = ['apple', 'banana', 'cherry']

x = fruits.index("cherry")

x

2

In [ ]:
L = ['a', 'b', 'c', 'd', 'e', 'f']
index = 1
x = L.pop(index)
print(f'The element {x} at index {index} was removed from the list')
print(f'The current list is {L}')

The element b at index 1 was removed from the list
The current list is ['a', 'c', 'd', 'e', 'f']

L.pop(index) removes the element at index in L and returns it. If no argument is provided to pop, index defaults to -1. index is thus a default argument for the method pop. A default value of -1 means that the last element in the list is removed. To see this an action, execute the following code:

In [ ]:
L = ['a', 'b', 'c', 'd', 'e', 'f']  #pop
x = L.pop()
print(f'The current list is {L}')

The current list is ['a', 'b', 'c', 'd', 'e']

In [ ]:
# The extend() method adds the specified list elements (or any iterable) to the end of the current list.
# list.extend(iterable)
fruits = ['apple', 'banana', 'cherry']

cars = ['Ford', 'BMW', 'Volvo']

fruits.extend(cars)

A list can be *reversed* in-place using the following method:

In [ ]:
L = [1, 2, 3, 4, 5]
print('Before:', L, id(L))
L.reverse()
print('After:', L, id(L))

Before: [1, 2, 3, 4, 5] 139880584179200
After: [5, 4, 3, 2, 1] 139880584179200

It is called in-place because the list before and after have the same id, i.e., they correspond to the same object. One must be careful while using methods that perform operations in-place.

In [ ]:
L_reversed = L.copy()
L_reversed.reverse()
print(L_reversed)
print(L)

[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]

Another useful method is *sort* which is used to sort lists in-place:

In [ ]:
L = [2, 1, 5, 6, 4, 3]
print('Before', L)
L.sort()
print('After', L)

Before [2, 1, 5, 6, 4, 3]
After [1, 2, 3, 4, 5, 6]

L.remove(x) *removes* the first (leftmost) occurrence of the element x in the list L

In [ ]:
L = [1, 2, 3, 4, 5] * 2
print('Before', L)
L.remove(1)
print('After', L)

Before [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
After [2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
if 5 in L:
  L.remove(5)

Trying to remove an element that is not there in the list will raise a ValueError with the message list.remove(x): x not in list. A safe way to remove items is as follows:

In [ ]:
L

[2, 3, 4, 1, 2, 3, 4, 5]

In [ ]:
# Start with an empty stack
stack = [ ]
# Append items to end of the stack; also called a push operation
stack.append('Harry Potter and the Philosopher\'s Stone')
stack.append('Harry Potter and the Chamber of Secrets')
# State of the stack
print(stack)
# Remove items from the end of the stack; also called a pop operation
stack.pop()
# State of the stack
print(stack)

["Harry Potter and the Philosopher's Stone", 'Harry Potter and the Chamber of Secrets']
["Harry Potter and the Philosopher's Stone"]

In [ ]:
# Start with an empty queue
queue = [ ]
# Insert elements at the beginning of the queue
queue.insert(0, 'Customer-1')
queue.insert(0, 'Customer-2')
# State of the queue
print(queue)
# Remove items from the queue
queue.pop()
# State of the queue
print(queue)

['Customer-2', 'Customer-1']
['Customer-2']

#### Strings and Lists
#####**split**

split is a string method that splits a string along a delimiter. A delimiter string is one or more characters that specify where to split the string. The output of the split operation is a list of strings that are split along the delimiter.

Lists make a frequent appearance while processing strings. Consider the following problem:

* Accept a sentence as input and find the number of words in it. Assume that it is a simple sentence with a single space separating consecutive words. There are no other punctuation marks in the sentence.

Let us look at a "list-less" solution first:

In [ ]:
# Solution-1
sentence = 'this sentence is false' # a simple sentence
count = 1
for char in sentence:
  if char == ' ':
    count += 1
print(count)

4

In [ ]:
# Solution-2
sentence = 'this sentence is false' # a simple sentence
words = sentence.split(' ')         # space is the delimiter used
print(words)
count = len(words)
print(count)

['this', 'sentence', 'is', 'false']
4

In [ ]:
comma_words = 'one,two,three,four'
numbers = comma_words.split(',')   # , is the delimiter used
print(numbers)

['one', 'two', 'three', 'four']

In [ ]:
some_str = 'allISwell'
words = some_str.split('IS')
print(words)

['all', 'well']

####**join**
Just as we went from a string to a list, we can also move from a list of strings to a string. Just as split chops a string along a delimiter, join stitches together the strings in a list, and the thread it uses is a space in this case. We could also stitch them together using any other string,

Consider the following problem:

Accept a sequence of words as input and construct a sentence out of it.

We will first look at a solution that doesn't use lists:

In [ ]:
words = ['this', 'sentence', 'is', 'false']
sentence = ''
for word in words:
    sentence += word + ' ' # sentence = sentence + word + ' '
    print(sentence)
print("Final:", sentence)

this
this sentence
this sentence is
this sentence is false
Final: this sentence is false

In [ ]:
words = ['this', 'sentence', 'is', 'false']
sentence = words[0]
for word in words[1 : ]:
    sentence = sentence+ ' ' + word
print(sentence)

this sentence is false

In [ ]:
words = ['this', 'sentence', 'is', 'false']
sentence = ' '.join(words)
print(sentence)

this sentence is false

In [ ]:
sentence = "one two three four get on the dance floor"
words = sentence.split(' ')  # return list of words separator by space
print(words)

again_sentence = ' '.join(words)
print(again_sentence)

['one', 'two', 'three', 'four', 'get', 'on', 'the', 'dance', 'floor']
one two three four get on the dance floor

deepcopy is a function from the library copy. We won't enter into how it works. Suffice to say that when using nested lists or any collection of mutable objects, use deepcopy if you wish to make a clean copy.

####Tuples
A tuple is an immutable sequence of values:

In [ ]:
family = ('father', 'mother', 'child')
print(type(family))
print(isinstance(family, tuple))

<class 'tuple'>
True

In [ ]:
print(family[0])
print(family[0:2])

father
('father', 'mother')

The main point of difference between lists and tuples is that tuples cannot be updated in-place since they are immutable. So, the following operation will throw an error:

In [ ]:
##### Alarm! Wrong code snippet! #####
numbers = ('one', 'two', 'four')
numbers[2] = 'three'
##### Alarm! Wrong code snippet! #####

In [ ]:
numbers = ('one', 'two', 'four', 'one')
print(numbers.count('one'))
print(numbers.index('two'))

2
1

In [ ]:
for num in (1,2,4):
  print(num)

1
2
4

In [ ]:
my_tup = (6,7,8,2)
print(sum(my_tup))
print(min(my_tup))
print(max(my_tup))

23
2
8

More on Tuples

A few more points on tuples.

A singleton tuple should be defined as follows:

In [ ]:
i_am_single = (1, )
print(len(i_am_single))
print(isinstance(i_am_single, tuple))

1
True

In [ ]:
i_am_single = (1)
print(isinstance(i_am_single, int))

True

A list can be converted into a tuple and vice versa:

In [ ]:
a_list = [1, 2, 3]
a_tuple = tuple(a_list)
b_tuple = (1, 2, 3)
b_list = list(b_tuple)

In [ ]:
#  tuple can hold a non-homogeneous sequence of items:
a_tuple = (1, 'cool', True)

# Membership can be determined using the in keyword:
1 in (1, 2, 3)  #True
'hello' in ('some', 'random', 'sequence')

False

In [ ]:
# Tuples can be nested:
a = ((1, 2, 3), (4, 5, 6))
print(a[0][2])

3

In [ ]:
# A tuple can hold mutable objects.
a_tuple = ([0, 1, 2], [4, 5, 6])
a_tuple[0][0] = 100

In [ ]:
a_tuple = ([0, 1, 2], [4, 5, 6])
print(id(a_tuple[0]))
a_tuple[0][0] = 100
print(id(a_tuple[0]))

139879726213888
139879726213888

In [ ]:
a_tuple

([100, 1, 2], [4, 5, 6])

We see that the id of the element inside the tuple remains unchanged. Thus the identities of the sequence of objects that make up a tuple can never change, and the interpreter will never allow that to change. If the objects inside the sequence are mutable — such as lists — then the values that they hold might change, but they continue to retain their identities.

In [ ]:
pairs =[]
for a in range(1,101):
  for b in range(1, 101):
    if a * b == 100:
      pairs.append((a,b))
print(pairs)

[(1, 100), (2, 50), (4, 25), (5, 20), (10, 10), (20, 5), (25, 4), (50, 2), (100, 1)]

Packing and Unpacking

In [ ]:
T = 1, 2, 3
print(T)
print(isinstance(T, tuple))

(1, 2, 3)
True

At first sight, line-1 seems to be an error. We have seen multiple assignment on the same line, perhaps we are two variables short on the LHS? But on execution, we see that there is no error. T is in fact the tuple (1, 2, 3). This is called tuple packing. The values 1, 2 and 3 are packed into a tuple. The reverse operation is called sequence unpacking:

In [ ]:
x, y, z = T
print(x, y, z)

1 2 3

In [ ]:
# Multiple assignment is a combination of tuple packing and sequence unpacking.

x, y, z = 1, 2, 3

#Dictionaries

In [ ]:
brics = {
    'Brazil' : 'Brasilia',
    'Russia' : 'Moscow',
    'India' : 'New Delhi',
    'China' : 'Beijing',
    'South Africa' : 'Pretoria'
}

In [ ]:
print(type(brics))
print(isinstance(brics, dict))

<class 'dict'>
True

In [ ]:
# To access the value corresponding to a given key, we do the following:
print(brics['India'], 'is the capital of', 'India')

New Delhi is the capital of India

In [ ]:
# The value corresponding to a given key can be updated:

# Moving to a different capital for South Africa
brics['South Africa'] = 'Cape Town'
print(brics)

{'Brazil': 'Brasilia', 'Russia': 'Moscow', 'India': 'New Delhi', 'China': 'Beijing', 'South Africa': 'Cape Town'}

In [ ]:
# Or we could also store all three capitals
brics['South Africa'] = ('Pretoria', 'Cape Town', 'Bloemfontein')
print(brics)

{'Brazil': 'Brasilia', 'Russia': 'Moscow', 'India': 'New Delhi', 'China': 'Beijing', 'South Africa': ('Pretoria', 'Cape Town', 'Bloemfontein')}

In [ ]:
L = ['hello','good', 'morning']

D_word_len = {}

for word in L:
  D_word_len[word] = len(word)

print(D_word_len)

{'hello': 5, 'good': 4, 'morning': 7}

The `key of a dictionary can be any immutable object`. Let us look at different combinations key-value pairs that are possible beginning with the basic types: int, str, float, bool:

In [ ]:
# int <> int
squares = {0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
# str <> int
months = {'Jan': 31, 'March': 31, 'May': 31, 'Nov': 30}
# int <> str
roll_numbers = {1: 'CS001', 2: 'CS002', 3: 'CS003'}
# str <> str
names = {'Rohit': 'Sharma', 'Saina': 'Nehwal'}
# str <> float
constants = {'pi': 3.14, 'e': 2.71}
# float <> str
fractions = {0.5: 'half', 0.25: 'quarter', 0.3: 'one-third'}
# int <> bool
binary = {0: True, 1: False}

Next, we have dictionaries that have list and tuple as the type of their values:

In [ ]:
# str <> list
outcomes = {'IND VS AUS': ['IND', 'AUS', 'IND', 'IND'],
            'IND VS ENG': ['IND', 'ENG']
            }
# float <> tuple
bounds = {1.7: (1, 2),
          4.3: (4, 5),
          -1.2: (-2, -1)
          }

In [ ]:
# tuple <> list
T1, T2 = (0, 1), (1, 2)
random_numbers = {T1: [0.1, 0.4, 0.9], T2: [1.1, 1.9]}

In [ ]:
random_numbers

{(0, 1): [0.1, 0.4, 0.9], (1, 2): [1.1, 1.9]}

More on Keys
Earlier, we have mentioned that the keys of dictionaries have to be immutable, but this statement is not entirely accurate. In this section, we will explore why. What happens if we use a list as a key?


```
##### Alarm! Wrong code snippet #####
some_list = [0, 1]

bad_dict = {some_list: 0}
##### Alarm! Wrong code snippet #####
```



It throws a TypeError with the following message: unhashable type: 'list'. A list cannot be a key in a dictionary; but the error message doesn't talk about immutability, instead it says that the list type is unhashable. A more accurate statement about keys in a dictionary is given below:

*The keys of a dictionary must be hashable.*

To understand what we mean by the term hashable, we shall briefly look at the way Python implements dictionaries. The following section on hash tables is a bit involved and can be skipped.

## Hash Tables
Python dictionaries are implemented using a data structure called a hash table. It is best to think about a hash table as a book-rack that has a number of rows. Picture the key-value pairs as books that are going to be stored in these racks. To access a book, we need to know the row number in which it is present. This is where the idea of a hash function comes in. The hash function is denoted by
 and converts the key to the row number.

The hash function accepts a key
 as input and returns a value,
, as output. This is called the hash value. In our analogy, the hash value is synonymous with the rack number. Once we know the rack number, the book (key-value) stored in it can be easily retrieved. The description is somewhat naive, but you get the point.

Now, an object in Python is hashable if it has a hash value which never changes during its lifetime and can be compared to other objects. Most of the immutable objects that we have seen so far are hashable: int, float, str, bool. Mutable containers such as lists are not hashable. So, can we just go back to the original definition and claim that all immutable objects can be used as keys in dictionaries? No! Consider the following example:
```
##### Alarm! Wrong code snippet #####
some_tuple = ([0, 1], [2, 3])
bad_dict = {some_tuple: 0}
##### Alarm! Wrong code snippet #####
```
Though some_tuple is immutable, it contains a sequence of lists which are mutable. According to the Python documentation, immutable containers are hashable only if their elements are hashable. So, *some_tuple* is not hashable, and hence it cannot be used as a key!

## Iterating over Dictionaries

In [ ]:
squares = {0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}    # key is a number, value is its square
for key in squares.keys():
    print(f'The square of {key} is {squares[key]}')

The square of 0 is 0
The square of 1 is 1
The square of 2 is 4
The square of 3 is 9
The square of 4 is 16
The square of 5 is 25

In [ ]:
squares = {0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}    # key is a number, value is its square
for key in squares:
    print(f'The square of {key} is {squares[key]}')

The square of 0 is 0
The square of 1 is 1
The square of 2 is 4
The square of 3 is 9
The square of 4 is 16
The square of 5 is 25

In [ ]:
squares.items()

dict_items([(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25)])

In [1]:
squares = {0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}    # key is a number, value is its square
for key, value in squares.items():
    print(f'The square of {key} is {value}')

The square of 0 is 0
The square of 1 is 1
The square of 2 is 4
The square of 3 is 9
The square of 4 is 16
The square of 5 is 25

Mutability
Like lists dictionaries are mutable objects. To see the mutability of dict objects in action, consider the following code:

In [2]:
dict_1 = {'one': 1, 'two': 2, 'three': 3}
dict_2 = dict_1
dict_2['four'] = 4
print(dict_1, dict_2)
print(dict_1 is dict_2)

{'one': 1, 'two': 2, 'three': 3, 'four': 4} {'one': 1, 'two': 2, 'three': 3, 'four': 4}
True

We see that dict_2 is alias of dict_1 and both point to the same object. If we want a new dict object with the same contents as dict_1, we could either use the copy() method or the dict built-in function:

In [3]:
dict_1 = {'one': 1, 'two': 2, 'three': 3}
dict_2 = dict_1.copy()      # dict(dict_1) also works
dict_2['four'] = 4
print(dict_1, dict_2)
print(dict_1 is not dict_2)

{'one': 1, 'two': 2, 'three': 3} {'one': 1, 'two': 2, 'three': 3, 'four': 4}
True

The last line prints True which confirms that we have two different objects. So modifying one doesn't affect the other. But note that copy() only produces a shallow copy. As long as the values are immutable, this doesn't matter. But if we have mutable values, then we have a problem:

In [4]:
dict_1 = {'one': [1], 'two': [1, 1], 'three': [1, 1, 1]}
dict_2 = dict_1.copy()
dict_2['one'].append(100)
print(dict_1, dict_2)
print(dict_1 is not dict_2)
print(dict_1['one'] is dict_2['one'])

{'one': [1, 100], 'two': [1, 1], 'three': [1, 1, 1]} {'one': [1, 100], 'two': [1, 1], 'three': [1, 1, 1]}
True
True

Here, we see that the value corresponding to the key 'one' in both dictionaries gets affected. This is because dict_1['one'] and dict_2['one'] are still the same object. This can be seen from the last statement of the code given above. To set this right, we need to do a deepcopy:

In [5]:
from copy import deepcopy
dict_1 = {'one': [1], 'two': [1, 1], 'three': [1, 1, 1]}
dict_2 = deepcopy(dict_1)
dict_2['one'].append(100)
print(dict_1, dict_2)
print(dict_1 is not dict_2)
print(dict_1['one'] is not dict_2['one'])

{'one': [1], 'two': [1, 1], 'three': [1, 1, 1]} {'one': [1, 100], 'two': [1, 1], 'three': [1, 1, 1]}
True
True

# Text processing

In [6]:
text = "In reality, programming languages are how programmers express and communicate ideas — and the audience for those ideas is other programmers, not computers. The reason: the computer can take care of itself, but programmers are always working with other programmers, and poorly communicated ideas can cause expensive flops. In fact, ideas expressed in a programming language also often reach the end users of the program — people who will never read or even know about the program, but who nevertheless are affected by it."

### Number of sentences

In [10]:
sentences = text.split('.')

In [8]:
for sentence in sentences:
  print(sentence)
print(f"There are {len(sentences)} sentences in this text.")

In reality, programming languages are how programmers express and communicate ideas — and the audience for those ideas is other programmers, not computers
 The reason: the computer can take care of itself, but programmers are always working with other programmers, and poorly communicated ideas can cause expensive flops
 In fact, ideas expressed in a programming language also often reach the end users of the program — people who will never read or even know about the program, but who nevertheless are affected by it

There are 4 sentences in this text.

In [12]:
# remove all empty strings in sentences
while '' in sentences:
  sentences.remove('')
print(f"There are {len(sentences)} sentences in this text.")

There are 3 sentences in this text.

### Number of words

In [13]:
words = []
for sentence in sentences:
  words_ = sentence.split(' ')
  words.extend(words_)

In [14]:
words

['In',
 'reality,',
 'programming',
 'languages',
 'are',
 'how',
 'programmers',
 'express',
 'and',
 'communicate',
 'ideas',
 '—',
 'and',
 'the',
 'audience',
 'for',
 'those',
 'ideas',
 'is',
 'other',
 'programmers,',
 'not',
 'computers',
 '',
 'The',
 'reason:',
 'the',
 'computer',
 'can',
 'take',
 'care',
 'of',
 'itself,',
 'but',
 'programmers',
 'are',
 'always',
 'working',
 'with',
 'other',
 'programmers,',
 'and',
 'poorly',
 'communicated',
 'ideas',
 'can',
 'cause',
 'expensive',
 'flops',
 '',
 'In',
 'fact,',
 'ideas',
 'expressed',
 'in',
 'a',
 'programming',
 'language',
 'also',
 'often',
 'reach',
 'the',
 'end',
 'users',
 'of',
 'the',
 'program',
 '—',
 'people',
 'who',
 'will',
 'never',
 'read',
 'or',
 'even',
 'know',
 'about',
 'the',
 'program,',
 'but',
 'who',
 'nevertheless',
 'are',
 'affected',
 'by',
 'it']

In [15]:
len(words)

86

enumerate() function adds a counter to each item in a list or other iterable. It turns the iterable into something we can loop through, where each item comes with its number (starting from 0 by default). We can also turn it into a list of (number, item) pairs using list().

In [16]:
for index, word in enumerate(words):
  print(index, word)

0 In
1 reality,
2 programming
3 languages
4 are
5 how
6 programmers
7 express
8 and
9 communicate
10 ideas
11 —
12 and
13 the
14 audience
15 for
16 those
17 ideas
18 is
19 other
20 programmers,
21 not
22 computers
23
24 The
25 reason:
26 the
27 computer
28 can
29 take
30 care
31 of
32 itself,
33 but
34 programmers
35 are
36 always
37 working
38 with
39 other
40 programmers,
41 and
42 poorly
43 communicated
44 ideas
45 can
46 cause
47 expensive
48 flops
49
50 In
51 fact,
52 ideas
53 expressed
54 in
55 a
56 programming
57 language
58 also
59 often
60 reach
61 the
62 end
63 users
64 of
65 the
66 program
67 —
68 people
69 who
70 will
71 never
72 read
73 or
74 even
75 know
76 about
77 the
78 program,
79 but
80 who
81 nevertheless
82 are
83 affected
84 by
85 it

In [18]:
list(enumerate(words))

[(0, 'In'),
 (1, 'reality,'),
 (2, 'programming'),
 (3, 'languages'),
 (4, 'are'),
 (5, 'how'),
 (6, 'programmers'),
 (7, 'express'),
 (8, 'and'),
 (9, 'communicate'),
 (10, 'ideas'),
 (11, '—'),
 (12, 'and'),
 (13, 'the'),
 (14, 'audience'),
 (15, 'for'),
 (16, 'those'),
 (17, 'ideas'),
 (18, 'is'),
 (19, 'other'),
 (20, 'programmers,'),
 (21, 'not'),
 (22, 'computers'),
 (23, ''),
 (24, 'The'),
 (25, 'reason:'),
 (26, 'the'),
 (27, 'computer'),
 (28, 'can'),
 (29, 'take'),
 (30, 'care'),
 (31, 'of'),
 (32, 'itself,'),
 (33, 'but'),
 (34, 'programmers'),
 (35, 'are'),
 (36, 'always'),
 (37, 'working'),
 (38, 'with'),
 (39, 'other'),
 (40, 'programmers,'),
 (41, 'and'),
 (42, 'poorly'),
 (43, 'communicated'),
 (44, 'ideas'),
 (45, 'can'),
 (46, 'cause'),
 (47, 'expensive'),
 (48, 'flops'),
 (49, ''),
 (50, 'In'),
 (51, 'fact,'),
 (52, 'ideas'),
 (53, 'expressed'),
 (54, 'in'),
 (55, 'a'),
 (56, 'programming'),
 (57, 'language'),
 (58, 'also'),
 (59, 'often'),
 (60, 'reach'),
 (61, 'the'),
 (62, 'end'),
 (63, 'users'),
 (64, 'of'),
 (65, 'the'),
 (66, 'program'),
 (67, '—'),
 (68, 'people'),
 (69, 'who'),
 (70, 'will'),
 (71, 'never'),
 (72, 'read'),
 (73, 'or'),
 (74, 'even'),
 (75, 'know'),
 (76, 'about'),
 (77, 'the'),
 (78, 'program,'),
 (79, 'but'),
 (80, 'who'),
 (81, 'nevertheless'),
 (82, 'are'),
 (83, 'affected'),
 (84, 'by'),
 (85, 'it')]

In [20]:
proc_words = [ ]
for word in words:
    if not(word == '' or word == '—'):
        proc_words.append(word)
print(f'There are {len(proc_words)} words in this text')

There are 82 words in this text

In [21]:
proc_words

['In',
 'reality,',
 'programming',
 'languages',
 'are',
 'how',
 'programmers',
 'express',
 'and',
 'communicate',
 'ideas',
 'and',
 'the',
 'audience',
 'for',
 'those',
 'ideas',
 'is',
 'other',
 'programmers,',
 'not',
 'computers',
 'The',
 'reason:',
 'the',
 'computer',
 'can',
 'take',
 'care',
 'of',
 'itself,',
 'but',
 'programmers',
 'are',
 'always',
 'working',
 'with',
 'other',
 'programmers,',
 'and',
 'poorly',
 'communicated',
 'ideas',
 'can',
 'cause',
 'expensive',
 'flops',
 'In',
 'fact,',
 'ideas',
 'expressed',
 'in',
 'a',
 'programming',
 'language',
 'also',
 'often',
 'reach',
 'the',
 'end',
 'users',
 'of',
 'the',
 'program',
 'people',
 'who',
 'will',
 'never',
 'read',
 'or',
 'even',
 'know',
 'about',
 'the',
 'program,',
 'but',
 'who',
 'nevertheless',
 'are',
 'affected',
 'by',
 'it']

In [22]:
uniq_words = dict()
for word in proc_words:
    if word not in uniq_words:
        uniq_words[word] = 0
    uniq_words[word] += 1
print(f'There are {len(uniq_words)} unique words in this text')

There are 62 unique words in this text

In [23]:
uniq_words

{'In': 2,
 'reality,': 1,
 'programming': 2,
 'languages': 1,
 'are': 3,
 'how': 1,
 'programmers': 2,
 'express': 1,
 'and': 3,
 'communicate': 1,
 'ideas': 4,
 'the': 5,
 'audience': 1,
 'for': 1,
 'those': 1,
 'is': 1,
 'other': 2,
 'programmers,': 2,
 'not': 1,
 'computers': 1,
 'The': 1,
 'reason:': 1,
 'computer': 1,
 'can': 2,
 'take': 1,
 'care': 1,
 'of': 2,
 'itself,': 1,
 'but': 2,
 'always': 1,
 'working': 1,
 'with': 1,
 'poorly': 1,
 'communicated': 1,
 'cause': 1,
 'expensive': 1,
 'flops': 1,
 'fact,': 1,
 'expressed': 1,
 'in': 1,
 'a': 1,
 'language': 1,
 'also': 1,
 'often': 1,
 'reach': 1,
 'end': 1,
 'users': 1,
 'program': 1,
 'people': 1,
 'who': 2,
 'will': 1,
 'never': 1,
 'read': 1,
 'or': 1,
 'even': 1,
 'know': 1,
 'about': 1,
 'program,': 1,
 'nevertheless': 1,
 'affected': 1,
 'by': 1,
 'it': 1}

In [24]:
print(uniq_words['programmers'])

2

In [25]:
for word in proc_words:
    if 'programmers' in word:
        print(word)

programmers
programmers,
programmers
programmers,

In [26]:
proc_words = [ ]
for word_ in words:
    word = word_.lower()
    if not(word == '' or word == '—'):
        if not word_.isalnum():
            word = word_[:-1]
        proc_words.append(word)
print(f'There are {len(proc_words)} words in this text')

There are 82 words in this text

In [27]:
uniq_words = dict()
for word in proc_words:
    if word not in uniq_words:
        uniq_words[word] = 0
    uniq_words[word] += 1
print(f'There are {len(uniq_words)} unique words in this text')

There are 58 unique words in this text

In [28]:
for word, freq in uniq_words.items():
    print(word, freq)

in 3
reality 1
programming 2
languages 1
are 3
how 1
programmers 4
express 1
and 3
communicate 1
ideas 4
the 6
audience 1
for 1
those 1
is 1
other 2
not 1
computers 1
reason 1
computer 1
can 2
take 1
care 1
of 2
itself 1
but 2
always 1
working 1
with 1
poorly 1
communicated 1
cause 1
expensive 1
flops 1
fact 1
expressed 1
a 1
language 1
also 1
often 1
reach 1
end 1
users 1
program 2
people 1
who 2
will 1
never 1
read 1
or 1
even 1
know 1
about 1
nevertheless 1
affected 1
by 1
it 1

In [29]:
for word, freq in enumerate(uniq_words):
    print(word, freq)

0 in
1 reality
2 programming
3 languages
4 are
5 how
6 programmers
7 express
8 and
9 communicate
10 ideas
11 the
12 audience
13 for
14 those
15 is
16 other
17 not
18 computers
19 reason
20 computer
21 can
22 take
23 care
24 of
25 itself
26 but
27 always
28 working
29 with
30 poorly
31 communicated
32 cause
33 expensive
34 flops
35 fact
36 expressed
37 a
38 language
39 also
40 often
41 reach
42 end
43 users
44 program
45 people
46 who
47 will
48 never
49 read
50 or
51 even
52 know
53 about
54 nevertheless
55 affected
56 by
57 it

In [30]:
total = 0
for word in uniq_words:
    total += uniq_words[word]
assert total == len(proc_words)

As the code doesn't raise any AssertionError, we are correct!

In [31]:
first_word = second_word = third_word = ''
first_val = second_val = third_val = 0
for word, freq in uniq_words.items():
    if freq > first_val:
        first_val, second_val, third_val = freq, first_val, second_val
        first_word, second_word, third_word = word, first_word, second_word
    elif freq > second_val and freq < first_val:
        second_val, third_val = freq, second_val
        second_word, third_word = word, second_word
    elif freq > third_val and freq < second_val:
        third_val = freq
        third_word = word
print(first_word, first_val)
print(second_word, second_val)
print(third_word, third_val)

the 6
programmers 4
in 3

In [32]:
mapping = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5,
           'f': 6 , 'g': 7, 'h': 8, 'i': 9, 'j': 10,
           'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15,
           'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20,
           'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25,
           'z': 26
          }

for letter, count in mapping.items():
    print(letter, count)

a 1
b 2
c 3
d 4
e 5
f 6
g 7
h 8
i 9
j 10
k 11
l 12
m 13
n 14
o 15
p 16
q 17
r 18
s 19
t 20
u 21
v 22
w 23
x 24
y 25
z 26

In [33]:
pangram = 'the quick brown fox jumps over the lazy dog'
words = pangram.split(' ')          # get list of words in the sentence
letters = ''.join(words)            # join the words back; eliminates spaces
sorted_letters = sorted(letters)    # sort letters
mapping, count = dict(), 0
for letter in sorted_letters:
    # check if letter is not present in dict
    # to avoid counting same letter multiple times
    if letter not in mapping:
        count += 1
        mapping[letter] = count     # map the letter to count

for letter, count in mapping.items():
    print(letter, count)

a 1
b 2
c 3
d 4
e 5
f 6
g 7
h 8
i 9
j 10
k 11
l 12
m 13
n 14
o 15
p 16
q 17
r 18
s 19
t 20
u 21
v 22
w 23
x 24
y 25
z 26

In [37]:
keys = mapping.keys()
print(keys)
keys_list = list(mapping.keys())
print(keys)
items_list = list(mapping.items())
print(items_list)

dict_keys(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'])
dict_keys(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'])
[('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5), ('f', 6), ('g', 7), ('h', 8), ('i', 9), ('j', 10), ('k', 11), ('l', 12), ('m', 13), ('n', 14), ('o', 15), ('p', 16), ('q', 17), ('r', 18), ('s', 19), ('t', 20), ('u', 21), ('v', 22), ('w', 23), ('x', 24), ('y', 25), ('z', 26)]

In [38]:
view = mapping.values()
view_list = list(view)

In [39]:
# All three views - keys, items, values - support membership tests:
print('a' in mapping.keys())
print(1 in mapping.values())
print(('a', 1) in mapping.items())

True
True
True

In [40]:
mapping['ab'] = 3           # some noise added to mapping
value = mapping.pop('ab')
print(value)
print('ab' not in mapping)

3
True

If key is a key in a dictionary D, D.pop(key) removes the key key in D and returns the value associated with it. Removing a key naturally removes the value associated with it. Dictionaries are aristocratic data structures: keys are higher up in the hierarchy and values depend on the keys for their existence.

Dictionaries in Action: LMS
The online degree portal — our virtual classroom — is called a learning Management system (LMS). In more accessible terms, an LMS is the software application that powers the portal. Have you ever wondered how your assignment submissions get recorded and graded? This is the question that we will try to answer in this lesson. At a high level, the LMS is made of two components: frontend and backend.

In [50]:
submission = {
                'name': 'Kapil Dev',
                'roll_number': 'BSC1001',
                'time': 'Sunday 18 April 2021 10:23:30 PM IST',
                'problems': [
                                {'id': '10001', 'selected': (0, 1)},
                                {'id': '10002', 'selected': (1, )},
                                {'id': '10003', 'selected': (3, )}
                            ]
              }

In [51]:
assignment_ = [
                {'id': '10001', 'answers': (0, 1), 'marks': 2.0},
                {'id': '10002', 'answers': (1, ), 'marks': 1.0 },
                {'id': '10003', 'answers': (2, ), 'marks': 2.0}
             ]
assignment = dict()
for problem in assignment_:
    problem_id = problem['id']
    answers = problem['answers']
    marks = problem['marks']
    assignment[problem_id] = {'answers': answers, 'marks': marks}

In [52]:
assign = {}
for problem in assignment_:
    problem_id = problem['id']
    answers = problem['answers']
    marks = problem['marks']
    assign[problem_id] = {'answers': answers, 'marks': marks}

In [53]:
def grader(assignment, submission):
    """Grading logic"""
    result = 0.0
    for problem in submission['problems']:
        problem_id = problem['id']
        selected = problem['selected']
        answers = assignment[problem_id]['answers']
        if answers == selected:
            result += assignment[problem_id]['marks']
    return result

# Sets
A set is an unordered collection with no duplicate elements [refer]. Unlike lists and tuples, there is no notion of order in a set. This is why it is called an unordered collection as opposed to a sequence. A set can be defined as follows:

In [55]:
even_nums = {2, 4, 6, 8, 10}
print(type(even_nums))
print(isinstance(even_nums, set))

<class 'set'>
True

Notice the similarity in syntax between sets and dictionaries. Both are enclosed within curly braces. While a dictionary has key-value pairs in it, a set just has a collection of values. A set in Python is a remarkably accurate representation of a mathematical set. Therefore, most of the properties that you are used to seeing in mathematical sets nicely carry over to Python sets. This connection is so strong that you can often forget that you are dealing with Python sets.

In [56]:
nums_1 = {2, 4, 6, 8, 10}
nums_2 = {2, 2, 4, 4, 6, 6, 8, 8, 10, 10}
print(nums_1, nums_2)
print(nums_1 == nums_2)
print(nums_1 is not nums_2)

{2, 4, 6, 8, 10} {2, 4, 6, 8, 10}
True
True

As stated before, sets do not support duplicate elements. We see that nums_1 and nums_2 are equal sets. However, they don't point to the same object. Sets support membership just like lists, tuples and dictionaries.

In [57]:
nums = {1, 2, 3, 4, 5}
print(1 in nums)
print(6 not in nums)

True
True

In [58]:
nums = {1, 2, 3, 4, 5}
print(f'Cardinality of nums is {len(nums)}')

Cardinality of nums is 5

In [ ]:
# Sets cannot be indexed. This is quite reasonable as they are not ordered collections. The following code will throw an error:
##### Alarm! Wrong code snippet! #####
some_set = {'this', 'is', 'a', 'set'}
print(some_set[0])
##### Alarm! Wrong code snippet! #####

Any hashable object can be added to sets. This means most of the immutable types such as int, float, str and tuple can be added to sets. A small caveat as far as tuples are concerned: a tuple of lists is unhashable and therefore cannot be added to sets.

In [59]:
a_set = {1.0, 'one', 1, True, (1, )}    # valid set
not_a_set = {([1, 2], [3, 4])}          # not a valid set

TypeError: unhashable type: 'list'

Iterating through Sets
Though a set is not a sequence, iterating through the elements of a set is supported.

In [60]:
nums = {1, 2, 3, 4, 5}
for num in nums:
    print(num)

1
2
3
4
5

In [61]:
# How do we define an empty set?
empty_set = set()
print(isinstance(empty_set, set))

True

In [64]:
num = 1
digits = set()
for i in range(100):
    num *= 7
    last = num % 10
    digits.add(last)  # add is a method used to add elements to a set.
print(digits)

{9, 3, 1, 7}

Set Operations

Mathematical sets are friendly objects. They routinely interact with each other through one of the following operations:

* Subset
* Superset
* Union
* Intersection
* Difference

In [65]:
A = {1, 3, 5}
B = {1, 2, 3, 4, 5}
print(A.issubset(B))    # method-1
print(A <= B)           # method-2

True
True

In [66]:
A = {1, 2, 3}
B = {1, 2, 3}
print(A <= B)   # method-1
print(A < B)    # method-2

True
False

In [67]:
A = {1, 3, 5}
B = {1, 2, 3, 4, 5}
B.issuperset(A)     # method-1
print(B >= A)       # method-2

True

In [68]:
A = {1, 3, 5}
B = {2, 4, 6}
C1 = A.union(B)     # method-1
C2 = A | B          # method-2
print(C1, C2)
print(C1 == C2)

{1, 2, 3, 4, 5, 6} {1, 2, 3, 4, 5, 6}
True

In [69]:
A1, A2, A3, A4 = {1}, {2, 3}, {4, 5, 6}, {7, 8, 9, 10}
B1 = A1.union(A2, A3, A4)   # method-1
B2 = A1 | A2 | A3 | A4      # method-2
print(B1, B2)
print(B1 == B2)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10} {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
True

In [70]:
A = {2, 4, 6}
B = {2, 4}
C1 = A.intersection(B)  # method-1
C2 = A & B              # method-2
print(C1, C2)
print(C1 == C2)

{2, 4} {2, 4}
True

In [71]:
even, odd = {2, 4, 6}, {1, 3, 5}
common = even & odd
assert common == set()

In [72]:
A = {1, 2, 3, 4}
B = {2, 4, 5}
C1 = A.difference(B)    # method-1
C2 = A - B              # method-2
print(C1, C2)
print(C1 == C2)
D1 = B.difference(A)    # method-1
D2 = B - A              # method-2
print(D1, D2)
print(D1 == D2)

{1, 3} {1, 3}
True
{5} {5}
True

To remove an element from the set, we can use the remove method:

In [73]:
A = {'this', 'is', 'a', 'set'}
print('Before', A)
A.remove('this')
print('After', A)

Before {'this', 'a', 'set', 'is'}
After {'a', 'set', 'is'}

Given a list L, extract all unique elements from it and store the result in another list, L_uniq. The order of elements does not matter.

In [74]:
L = [1, 2, 3, 3, 4, 5, 6, 1, 2, 2]
S = set(L)
L_uniq = list(S)
print(L_uniq)

[1, 2, 3, 4, 5, 6]

Mutability

Sets are mutable entities.

In [75]:
A = {1, 2, 3}
B = A
B.add(4)
print(A, B)
print(A is B)

{1, 2, 3, 4} {1, 2, 3, 4}
True

A and B are the same objects. As before, there are two ways to do a shallow copy:

In [76]:
A = {1, 2, 3}
B1 = A.copy()
B2 = set(A)
B1.add(4)
B2.add(0)
print(A, B1, B2)
print(A is not B1)
print(A is not B2)

{1, 2, 3} {1, 2, 3, 4} {0, 1, 2, 3}
True
True

## Opening and reading from a file

In [77]:
f = open('examples.txt', 'r')
for line in f:
  print(line)
f.close()

FileNotFoundError: [Errno 2] No such file or directory: 'examples.txt'

In [78]:
f = open('writing.txt', 'w')
f.write('one ')
f.write('two ')
f.write('three ')
f.write('four ')
f.write('five')
f.close()

In [79]:
f = open('writing.txt', 'w')
f.write('one\n')
f.write('two\n')
f.write('three\n')
f.write('four\n')
f.write('five')
f.close()

To read a file, we open it in the read mode:

In [ ]:
f = open('<file_name>', 'r')
# ...
# code for reading something from file
# ...
f.close()

To write to a file, we open it in the write mode:

In [ ]:
f = open('<file_name>', 'w')
# ...
# code for writing something into the file
# ...
f.close()

In [81]:
f = open('writing.txt', 'r')
content = f.read()
print(content)
f.close()

one
two
three
four
five

ead() is a method defined for the file object. When it is called without any argument, it returns a string that contains the entire content of the file.

In [82]:
f = open('writing.txt', 'r')
for line in f:
    print(line)
    # line ends with a \n character for all lines except the last one
    # this is why we get an empty line between consecutive lines in the console
f.close()

one

two

three

four

five

In [84]:
f = open('writing.txt', 'r')
line1 = f.readline()
line2 = f.readline()
line3 = f.readline()
line4 = f.readline()
line5 = f.readline()
f.close()

In [85]:
line1

'one\n'

readline()
As its name suggests, the readline() method reads from the file one line at a time:

In [87]:
f = open('writing.txt', 'r')
line = f.readline()
while line != '':
    print(line, end = '')
    line = f.readline()
f.close()

one
two
three
four
five

readlines()
Finally, Python also provides a way to read the file and store it as a list of lines:

In [89]:
f = open('writing.txt', 'r')
lines = f.readlines()
for line in lines:
    print(line.strip())
f.close()

one
two
three
four
five

In [90]:
lines

['one\n', 'two\n', 'three\n', 'four\n', 'five']

In [91]:
f = open('writing.txt', 'w')
lines = ['one', 'two', 'three', 'four', 'five']
for line in lines:
    f.write(line + '\n')
f.close()

Reading CSV files

In [92]:
f = open('table.csv', 'r')
for line in f:
    print(line.strip())
f.close()

# Name,Physics,Mathematics,Chemistry
# Newton,100,98,90
# Einstein,100,85,88
# Ramanujan,70,100,70
# Gauss,100,100,70

FileNotFoundError: [Errno 2] No such file or directory: 'table.csv'

In [ ]:
f = open('table.csv', 'r')
for line in f:
    line = line.strip()
    columns = line.split(',')
    chem_marks = int(columns[-1])
    print(chem_marks)
f.close()

In [93]:
line = 'Newton,100,98,90'
line = line.strip()
columns = line.split(',')
chem_marks = int(columns[-1])
print(chem_marks)

90

# Objects and Classes

**Objects are entities that have certain attributes along with operations associated with them.**

For example, cars on the road could have the following attributes: speed, fuel level. The operations associated with it could be: start, stop, accelerate, decelerate, fill fuel tank. Given this basic understanding of what we mean by objects, we are now ready to define a class:

**A class is a blueprint or a template that is used to create objects.**

Think about a class as a Google form. A form is nothing but a template. The template is created once and then it is distributed. Each of us fills this form differently hence creating different objects.

**Object Oriented Programming (OOP) is a paradigm that looks at the world as a collection of objects and the interactions among them.**

OOP in Python: an example
Consider a very simple template for a student that has following information:

* Name
* Marks

We want to perform the following operations:

* Update the marks of the student
* Print student details

In [97]:
class Student:
  def __init__(self, name, marks):   #constructor
    self.name = name
    self.marks = marks

  def update_marks(self, marks):
    self.marks = marks

  def print_details(self):
    print(f'{self.name} : {self.marks}')

class is a keyword in Python to define classes. It is similar to the def keyword that is used to define functions. Student is the name of the class that we are creating. Within the class, we see that there are three functions: __init__, update_marks and print_details. Functions defined inside a class are given a special name, they are called methods of the class. Among the methods that can be defined for a class, __init__ holds a special place and is called the constructor. Let us first see how to create an object of type Student:

In [100]:
anish = Student('Anish', 80)

In [101]:
print(type(anish))

<class '__main__.Student'>

Notice that we have used the name of the class in the RHS of the assignment statement. This invokes what is called the constructor — __init__() method — of the class. Since the constructor has two parameters (ignore self for now) name and marks, we have to pass them as arguments while creating the object.

The two arguments are then assigned to self.name and self.marks respectively. These two variables are called the attributes of the object. Attributes can be accessed using the **.** operator:

In [102]:
print(anish.name)
print(anish.marks)

Anish
80

__init__(), update_marks() and print_details() are called methods. A method is effectively just a function that is defined in a class. Methods can be accessed using an object. If we wish to update Anish's marks to 95, then we invoke the method using the object anish:

In [103]:
anish.update_marks(95)

In [104]:
print(anish.marks)

95

In [105]:
anish.print_details()

Anish : 95

To summarize, anish is an object of type Student having two attributes — name and marks — that can be accessed using the . operator. This object is also equipped with two methods (ignoring the constructor), one to update the marks and the other to print the details of the object. Attributes define the state of an object. Different objects of the same class could have different attributes. Naively speaking, methods help to update the values of the attributes. Therefore, the methods capture the behaviour of the object.

## self

Some of you might be wondering about the variable self that crops in so many places in the definition of the class. The variable self is used to point to the current object. To get a better understanding, let us create two different Student objects:

In [106]:
anish = Student('Anish', 90)
lakshmi = Student('Lakshmi', 95)

In [107]:
lakshmi.print_details()


# When this method is called, Python actually ends up invoking the following function:
# Student.print_details(lakshmi)

Lakshmi : 95

In [ ]:
anish.update_marks(95)

# This is equivalent to the function call:
# Student.update_marks(anish, 95)

In [112]:
class Fruits:
  def __init__(self, name, favorite):
    self.name = name
    self.favorite = favorite

  def print_details(self):
    print(f'{self.name} : {self.favorite}')

In [121]:
mango = Fruits('Mango', True)
apple = Fruits('Apple', False)

In [122]:
mango.print_details()

Mango : True

In [123]:
apple.print_details()

Apple : False

# Class Attributes vs Object Attributes
So far all attributes that we have seen are object attributes. Given an attribute, say name or marks, it is different for different objects. The name attribute of anish is different from the corresponding attribute fo the object lakshmi. Now, we shall see another kind of attribute.

Let us say that we wish to keep track of the number students in our program. That is, when a new student joins our program, we need to update a counter. How do we do that? We need an attribute that is common to all objects and is not tied to any individual object. At the same time, we should be able to update this attribute whenever a new object is created. This is where the concept of class attributes comes in:

In [124]:
class Student:
    counter = 0
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks
        Student.counter += 1

    def update_marks(self, marks):
        self.marks = marks

    def print_details(self):
        print(f'{self.name}:{self.marks}')

In [125]:
madhavan = Student('Madhavan', 90)
print('Number of students in the program =', Student.counter)
andrew = Student('Andrew', 85)
print('Number of students in the program =', Student.counter)
usha = Student('Usha', 95)
print('Number of students in the program =', Student.counter)

Number of students in the program = 1
Number of students in the program = 2
Number of students in the program = 3

In [126]:
print(madhavan.counter)

3

A class attribute can be accessed by any of the objects. But, now, try to run this code:

In [127]:
madhavan.counter = -1
print("Student counter:", Student.counter)
print("Madhavan counter:", madhavan.counter)

Student counter: 3
Madhavan counter: -1

This seems confusing! But a moment's thought will convince you that it is not so hard. In line 20, we are creating an object attribute with the same name as the class attribute! If the same attribute name occurs in both an object and a class, then Python prioritizes the object attribute. In other words, when we change madhavan.counter, Student.counter remains unchanged because madhavan.counter gets delinked from Student.counter and becomes a new object attribute specific to madhavan

In [128]:
print("Usha counter:", usha.counter)
print("Madhavan counter:", madhavan.counter)
Rohan = Student('Rohan', 40)
print("Student counter:", Student.counter)
print("Usha counter:", usha.counter)
print("Madhavan counter:", madhavan.counter)

Usha counter: 3
Madhavan counter: -1
Student counter: 4
Usha counter: 4
Madhavan counter: -1

This demonstrates an important fact: class attributes cannot be updated by an object! At best, they can be referenced or accessed using an object

object attributes can be created dynamically during runtime. We have created three more object attributes on the fly. It is interesting to note the subtle difference between the attribute name and the three new attributes maths, physics and chem. Any object of Student will have the attribute name when it is initially created, of course with a different value for name depending on the object. But the attributes maths, physics and chem are unique to the object anish.

In [129]:
class Student:
    def __init__(self, name):
        self.name = name

anish = Student('Anish')
anish.maths = 100
anish.physics = 90
anish.chem = 70

# Inheritance
**Classes that are lower in the hierarchy inherit features or attributes from their ancestors.**

Example

By now you would have worked on plenty of assignments across multiple courses. Each assignment is a collection of questions. Questions come in different types, some are NAT, some MCQ. So, a NAT question is not of the same type as a MCQ question. Yet, both are questions. So, we see that there is a hierarchy of relationships here:

In [131]:
class Question:
    def __init__(self, statement, marks):
        self.statement = statement
        self.marks = marks

    def print_question(self):
        print(self.statement)

    def update_marks(self, marks):
        self.marks = marks

Note that we have only retained those elements as attributes that are common to all questions, irrespective of the type:

* statement of the question
* marks for the question

The next step is to define two new classes for the children of Question, one for MCQ and the other for NAT.

In [132]:
class NAT(Question):
    def __init__(self, statement, marks, answer):
        super().__init__(statement, marks)
        self.answer = answer

    def update_answer(self, answer):
        self.answer = answer

The super() function points to the parent class, in this case Question. So, in line 13, we are effectively calling the constructor of the parent class. If we need to update the marks, we can just invoke the method update_marks() that is inherited from Question:

In [133]:
q_nat = NAT('What is 1 + 1?', 1, 2)
q_nat.update_marks(4)
print(q_nat.marks)

4

In Python, the syntax used to make this dependency explicit is as follows:

class Derived(Base):
    def __init__(self, ...):
        pass

#### OR ####
class Child(Parent):
    def __init__(self, ...):
        ...

## Method Overriding

Sometimes we may want to modify the behaviour of existing methods in the parent class. For example, take the case of a MCQ question. For questions of this type, the statement of a problem is incomplete without the options. The print_question() method in the parent class just prints the statement, but it makes more sense to print the options as well for a MCQ question. So, we want the print_question() to behave differently. Though we have inherited this method from the parent class, we can override the behaviour of the method in the following way:

In [134]:
class MCQ(Question):
    def __init__(self, statement, marks, ops, c_ops):
        super().__init__(statement, marks)
        self.ops = ops      # list of all options
        self.c_ops = c_ops  # list of correct options

    def print_question(self):
        super().print_question()
        # Assume there are only four options
        op_index = ['(a)', '(b)', '(c)', '(d)']
        for i in range(4):
            print(op_index[i], self.ops[i])

Note that the parent class Question already prints the statement. So, we piggy-back on this behaviour using the super() function in line-8. In addition, we also print the options. Let us create a MCQ question object and see how it all works:

In [135]:
q_mcq = MCQ('What is the capital of India?',
           2,
           ['Chennai', 'Mumbai', 'Kolkota', 'New Delhi'],
           ['New Delhi'])
q_mcq.print_question()

What is the capital of India?
(a) Chennai
(b) Mumbai
(c) Kolkota
(d) New Delhi